const svg=document.querySelector('#canvas'), ns='http://www.w3.org/2000/svg';
const input=id=>document.querySelector(`#${id}`), layer=name=>document.querySelector(`[data-layer=${name}]`).checked;
const colors=['#1864ab','#e67700']; let mapData,planData,drawTarget=null,firstCorner=null,animationFrame=null;
let regions=[null,null], animation=null;
const strategyNames={global_scanline:'Global Scanline（全局扫描线）',bcd:'Cellular Decomposition（BCD）'};
const strategyHelp={global_scanline:'直接在整个有效区域铺设扫描线，经边界与障碍裁剪后得到 coverage lanes。',bcd:'先将复杂自由区域分解为 BCD cells，再为各 cell 生成规则 coverage lanes。'};
function el(tag,attrs={},cls){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(cls)n.setAttribute('class',cls);return n}
const points=ring=>ring.map(p=>`${p[0]},${-p[1]}`).join(' ');
function rings(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates.map((r,i)=>({ring:r,hole:i>0}));if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map((r,i)=>({ring:r,hole:i>0})));return[]}
function polygons(g){if(!g)return[];if(g.type==='Polygon')return[g.coordinates];if(g.type==='MultiPolygon')return g.coordinates;return[]}
function ringPath(ring){return ring.map((p,i)=>`${i?'L':'M'}${p[0]} ${-p[1]}`).join(' ')+' Z'}
function addGeometry(g,cls,style=''){polygons(g).forEach(p=>svg.append(el('path',{d:p.map(ringPath).join(' '),style,'fill-rule':'evenodd'},cls)))}
function addSegment(a,b,cls,style=''){svg.append(el('line',{x1:a.x,y1:-a.y,x2:b.x,y2:-b.y,style},cls))}
function drawCompletionPoint(point,index){const size=.9,y=-point.y,triangle=el('polygon',{points:`${point.x},${y-size} ${point.x+size},${y+size*.75} ${point.x-size},${y+size*.75}`},'completion-point'),title=el('title');title.textContent=`飞行前覆盖补全点 ${index+1} · ${point.id}`;triangle.append(title);svg.append(triangle)}
function drawCoverageCell(cell,droneIndex){const group=el('g',{},'coverage-cell'),cellColors=droneIndex?['#e67700','#c2410c','#b45309']:['#1864ab','#087f5b','#5f3dc4'],color=cellColors[cell.index%cellColors.length];rings(cell.geometry).filter(x=>!x.hole).forEach(x=>{const polygon=el('polygon',{points:points(x.ring),style:`fill:${color};stroke:${color}`},'coverage-cell-boundary'),title=el('title');title.textContent=`C${cell.index+1} · ${cell.area_m2.toFixed(1)} 平方米`;polygon.append(title);group.append(polygon)});const [x,y]=cell.label_point,badge=el('rect',{x:x-4.5,y:-y-3.2,width:9,height:6.4},'coverage-cell-label-bg'),label=el('text',{x,y:-y,'text-anchor':'middle','dominant-baseline':'central'},'coverage-cell-label');label.textContent=`C${cell.index+1}`;group.append(badge,label);svg.append(group)}
function addCoveragePatterns(){const defs=el('defs');colors.forEach((color,i)=>{const pattern=el('pattern',{id:`coverage-pattern-${i}`,width:4,height:4,patternUnits:'userSpaceOnUse',patternTransform:'rotate(35)'});pattern.append(el('rect',{width:4,height:4,fill:color,'fill-opacity':.08}));pattern.append(el('line',{x1:0,y1:0,x2:0,y2:4,stroke:color,'stroke-width':1,'stroke-opacity':.5}));defs.append(pattern)});svg.append(defs)}
function configureViewport(){const [a,b,c,d]=mapData.background.content_bounds,padX=24,padY=18;svg.setAttribute('viewBox',`${a-padX} ${-d-padY} ${c-a+2*padX} ${d-b+2*padY}`)}
function drawMapReference(){const [a,b,c,d]=mapData.background.content_bounds;
 svg.append(el('rect',{x:a,y:-d,width:c-a,height:d-b},'map-frame'));
 const g=el('g',{},'map-reference'),minor=10,major=50;
 for(let x=Math.ceil(a/minor)*minor;x<=c+1e-6;x+=minor){const isMajor=Math.abs(x/major-Math.round(x/major))<1e-6,len=isMajor?5:2.5;g.append(el('line',{x1:x,y1:-b,x2:x,y2:-b+len},isMajor?'axis-major':'axis-minor'));if(isMajor){const t=el('text',{x,y:-b+10,'text-anchor':'middle'},'axis-label');t.textContent=`${x}`;g.append(t)}}
 for(let y=Math.ceil(b/minor)*minor;y<=d+1e-6;y+=minor){const isMajor=Math.abs(y/major-Math.round(y/major))<1e-6,len=isMajor?5:2.5;g.append(el('line',{x1:a,y1:-y,x2:a-len,y2:-y},isMajor?'axis-major':'axis-minor'));if(isMajor){const t=el('text',{x:a-7,y:-y+1.5,'text-anchor':'end'},'axis-label');t.textContent=`${y}`;g.append(t)}}
 const xTitle=el('text',{x:(a+c)/2,y:-b+16,'text-anchor':'middle'},'axis-title');xTitle.textContent='ENU 东向 x（米）';g.append(xTitle);
 const yTitle=el('text',{x:a-19,y:-(b+d)/2,'text-anchor':'middle',transform:`rotate(-90 ${a-19} ${-(b+d)/2})`},'axis-title');yTitle.textContent='ENU 北向 y（米）';g.append(yTitle);
 const cx=c-23,cy=-d+32;
 g.append(el('line',{x1:cx,y1:cy,x2:cx,y2:cy-18},'compass-line'));
 g.append(el('polygon',{points:`${cx},${cy-22} ${cx-3},${cy-16} ${cx+3},${cy-16}`},'compass-arrow'));
 const north=el('text',{x:cx,y:cy-25,'text-anchor':'middle'},'map-label');north.textContent='北 N';g.append(north);
 g.append(el('line',{x1:cx,y1:cy,x2:cx+17,y2:cy},'compass-line'));
 g.append(el('polygon',{points:`${cx+21},${cy} ${cx+15},${cy-3} ${cx+15},${cy+3}`},'compass-arrow'));
 const east=el('text',{x:cx+24,y:cy+1.5},'map-label');east.textContent='东 E';g.append(east);svg.append(g)}
function defaultRegions(){const [a,b,c,d]=mapData.background.content_bounds,m=(a+c)/2;regions=[rectGeo(a,b,m,d),rectGeo(m,b,c,d)]}
function rectGeo(x1,y1,x2,y2){const a=Math.min(x1,x2),b=Math.min(y1,y2),c=Math.max(x1,x2),d=Math.max(y1,y2);return{type:'Polygon',coordinates:[[[a,b],[c,b],[c,d],[a,d],[a,b]]]}}
function draw(){svg.innerHTML='';if(!mapData)return;addCoveragePatterns();const [a,b,c,d]=mapData.background.bounds;if(layer('background'))svg.append(el('image',{href:`${mapData.background.url}?v=3`,x:a,y:-d,width:c-a,height:d-b,preserveAspectRatio:'none'}));
 addGeometry(mapData.search_area,'search-boundary');
 (mapData.excluded_search_regions??[]).forEach(r=>addGeometry(r.geometry,'excluded-search','fill:#343a40;fill-opacity:.42;stroke:#111;stroke-width:.45px;stroke-dasharray:1.5 1'));
 regions.forEach((g,i)=>addGeometry(g,`responsibility responsibility-${i+1}`,`fill:${colors[i]};fill-opacity:.10;stroke:${colors[i]};stroke-width:1px`));
 const drones=planData?.drones??[];
 if(layer('coverage'))drones.forEach((d,i)=>{if(animation){animation[i].revealed.forEach(g=>addGeometry(g,'viewpoint-coverage',`fill:${colors[i]};fill-opacity:.075;stroke:${colors[i]};stroke-opacity:.22;stroke-width:.12px`))}else addGeometry(d.summary.visible_detection_area,'valid-coverage',`fill:url(#coverage-pattern-${i});stroke:${colors[i]};stroke-opacity:.9;stroke-width:.65px`)});
 if(layer('patches'))drones.forEach((d,i)=>(d.summary.patches??[]).forEach(p=>addGeometry(p.geometry,p.covered?'patch':'patch uncovered',`fill:${p.covered?colors[i]:'#d95d5d'};fill-opacity:.13;stroke:#fff;stroke-width:.1px`)));
 if(layer('buildings'))mapData.buildings.forEach(bu=>{const [x1,y1,x2,y2]=bu.bounds,r=el('rect',{x:x1,y:-y2,width:x2-x1,height:y2-y1},'building'),t=el('title');t.textContent=`${bu.id} · 高度 ${bu.height_m.toFixed(1)} 米`;r.append(t);svg.append(r)});
 drones.forEach((d,i)=>{const summary=d.summary,route=summary.flight_waypoints??[],byId=Object.fromEntries(route.map(w=>[w.id,w]));if(layer('cells'))(summary.coverage_cells??[]).forEach(cell=>drawCoverageCell(cell,i));(summary.route_segments??[]).forEach(segment=>{const a=byId[segment.start_waypoint_id],b=byId[segment.end_waypoint_id];if(!a||!b)return;if(segment.kind==='coverage_lane'&&layer('lanes'))addSegment(a,b,'lane-route',`stroke:${colors[i]}`);if(segment.kind!=='coverage_lane'&&layer('transitions'))addSegment(a,b,'transition-route',`stroke:${i?'#9c4f00':'#7048a8'}`)});(summary.completion_points??[]).forEach(drawCompletionPoint);if(layer('waypoints'))route.forEach(w=>svg.append(el('circle',{cx:w.x,cy:-w.y,r:.75,style:`fill:${colors[i]}`},'waypoint')))});
 [0,1].forEach(i=>{const h=[+input(`home${i+1}-x`).value,+input(`home${i+1}-y`).value];if(h.every(Number.isFinite))svg.append(el('circle',{cx:h[0],cy:-h[1],r:2,style:`fill:${colors[i]}`},'home'))});drawAnimation();drawMapReference()}
function drawAnimation(){if(!animation)return;animation.forEach((s,i)=>{if(s.position)svg.append(el('circle',{id:`animation-drone-${i}`,cx:s.position[0],cy:-s.position[1],r:1.7,style:`fill:${colors[i]}`},'drone'))})}
function appendAnimatedCoverage(g,i){if(!layer('coverage'))return;rings(g).filter(x=>!x.hole).forEach(x=>svg.append(el('polygon',{points:points(x.ring),style:`fill:${colors[i]};fill-opacity:.075;stroke:${colors[i]};stroke-opacity:.22;stroke-width:.12px`},'viewpoint-coverage')))}
function updateAnimationDom(added){animation.forEach((s,i)=>{const drone=svg.querySelector(`#animation-drone-${i}`);if(drone){drone.setAttribute('cx',s.position[0]);drone.setAttribute('cy',-s.position[1])}added[i].forEach(g=>appendAnimatedCoverage(g,i))})}
function replay(){const drones=planData?.drones;if(!drones)return;cancelAnimationFrame(animationFrame);animation=drones.map(d=>{const route=d.summary.flight_waypoints,total=route.slice(1).reduce((sum,w,j)=>sum+Math.hypot(w.x-route[j].x,w.y-route[j].y),0);return{segment:0,progress:0,last:null,position:[route[0].x,route[0].y],distance:0,total,revealed:[]}});input('replay').disabled=true;draw();
 function step(time){let active=false;const added=[[],[]];animation.forEach((s,i)=>{const summary=drones[i].summary,route=summary.flight_waypoints,samples=summary.visibility_samples;if(s.segment>=route.length-1){while(s.revealed.length<samples.length){const g=samples[s.revealed.length].geometry;s.revealed.push(g);added[i].push(g)}return}active=true;if(s.last===null)s.last=time;const dt=Math.min(50,time-s.last);s.last=time;const a=route[s.segment],b=route[s.segment+1],dist=Math.hypot(b.x-a.x,b.y-a.y);s.progress+=dist?dt/1000*(10+18*+input('speed').value)/dist:1;const r=Math.min(1,s.progress);s.position=[a.x+(b.x-a.x)*r,a.y+(b.y-a.y)*r];const routeProgress=(s.distance+dist*r)/Math.max(s.total,1);while(s.revealed.length<samples.length&&samples[s.revealed.length].route_progress<=routeProgress){const g=samples[s.revealed.length].geometry;s.revealed.push(g);added[i].push(g)}if(r===1){s.distance+=dist;s.segment++;s.progress=0}});updateAnimationDom(added);if(active)animationFrame=requestAnimationFrame(step);else input('replay').disabled=false}animationFrame=requestAnimationFrame(step)}
function mapPoint(event){let p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;p=p.matrixTransform(svg.getScreenCTM().inverse());return[p.x,-p.y]}
document.querySelectorAll('.draw-region').forEach(b=>b.onclick=()=>{drawTarget=+b.dataset.drone;firstCorner=null;input('draw-tip').textContent=`正在绘制无人机 ${drawTarget+1} 责任区：请点击第一个对角`;input('draw-tip').style.display='block'});
svg.onclick=e=>{if(drawTarget===null)return;const p=mapPoint(e);if(!firstCorner){firstCorner=p;input('draw-tip').textContent='请点击另一个对角'}else{regions[drawTarget]=rectGeo(...firstCorner,...p);drawTarget=null;firstCorner=null;input('draw-tip').style.display='none';planData=null;draw()}};
svg.onmousemove=e=>{const p=mapPoint(e);input('coords').textContent=`ENU 东向 ${p[0].toFixed(1)}，北向 ${p[1].toFixed(1)}`};
function syncGeneratorLayers(){const cells=document.querySelector('[data-layer=cells]'),isBcd=input('generator').value==='bcd';cells.disabled=!isBcd;cells.checked=isBcd;cells.parentElement.title=isBcd?'显示 BCD 分解后的 cell 边界和编号':'Global Scanline 不生成 BCD cells'}
document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=draw);['home1-x','home1-y','home2-x','home2-y'].forEach(id=>input(id).oninput=draw);input('replay').onclick=replay;input('generator').onchange=()=>{input('generator-help').textContent=strategyHelp[input('generator').value];syncGeneratorLayers();planData=null;animation=null;draw()};syncGeneratorLayers();
function payload(){return{drones:[0,1].map(i=>({drone_id:`drone_${i+1}`,search_geometry:regions[i],home_x_m:+input(`home${i+1}-x`).value,home_y_m:+input(`home${i+1}-y`).value})),flight_altitude_m:+input('alt').value,horizontal_clearance_m:+input('hc').value,vertical_clearance_m:+input('vc').value,scan_direction_deg:null,coverage_generation_method:input('generator').value,route_optimization_method:'auto',completion_strategy:input('completion-strategy').value,video_analysis_rate_hz:+input('frequency').value,control_point_spacing_m:+input('control-spacing').value,coverage_speed_mps:+input('lane-speed').value,connector_speed_mps:+input('connector-speed').value,obstacle_speed_mps:+input('obstacle-speed').value,return_speed_mps:+input('connector-speed').value,camera:{image_width_px:1920,image_height_px:1080,horizontal_fov_deg:+input('hfov').value,vertical_fov_deg:+input('vfov').value,pitch_deg:-90,yaw_mode:'follow_path',forward_overlap:+input('fo').value,side_overlap:+input('so').value,target_width_m:+input('target-width').value,target_length_m:+input('target-length').value,target_height_m:+input('target-height').value,image_boundary_margin_ratio:+input('image-margin').value}}}
function errorMessage(detail,status){if(typeof detail==='string')return detail;if(Array.isArray(detail))return detail.map(item=>`${(item.loc??[]).slice(1).join(' → ')||'请求参数'}：${item.msg??JSON.stringify(item)}`).join('；');if(detail&&typeof detail==='object')return JSON.stringify(detail);return`规划失败（${status}）`}
let planningTimerHandle=null,planningHistory=[];
function startPlanningTimer(startedAt){clearInterval(planningTimerHandle);const timer=input('planning-timer');timer.classList.add('running');const update=()=>{timer.textContent=`${((performance.now()-startedAt)/1000).toFixed(1)} 秒`};update();planningTimerHandle=setInterval(update,100)}
function stopPlanningTimer(startedAt){clearInterval(planningTimerHandle);planningTimerHandle=null;const elapsed=(performance.now()-startedAt)/1000,inputTimer=input('planning-timer');inputTimer.textContent=`${elapsed.toFixed(3)} 秒`;inputTimer.classList.remove('running');return elapsed}
function addPlanningHistory(body,elapsed,error){const strategy=input('completion-strategy').value,item={time:new Date().toLocaleTimeString(),strategy,elapsed,error,body};planningHistory.unshift(item);input('planning-history').innerHTML=planningHistory.map((record,index)=>{const success=!!record.body,backend=success?`${record.body.planning_time_s.toFixed(3)} 秒`:'--',droneLines=success?record.body.drones.map((drone,i)=>{const s=drone.summary;return`无人机 ${i+1}：${s.coverage_requirement_met?'可执行':'覆盖不足'}，${(100*s.coverage_ratio).toFixed(6)}%，${s.path_length_m.toFixed(0)} 米`}).join('<br>'):`失败：${record.error}`;return`<div class="history-item ${success?'success':'failure'}"><p><strong>#${planningHistory.length-index} ${record.time}</strong> · ${record.strategy}</p><p>浏览器等待 ${record.elapsed.toFixed(3)} 秒 · 后端规划 ${backend}</p><p>${droneLines}</p></div>`}).join('')}
input('plan').onclick=async()=>{const button=input('plan'),startedAt=performance.now();let historyBody=null,historyError='';startPlanningTimer(startedAt);input('error').style.display='none';button.disabled=true;button.textContent='正在生成并优化…';try{const r=await fetch('/api/plan-dual',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())}),text=await r.text();let body;try{body=JSON.parse(text)}catch{throw new Error(`规划服务返回异常（状态码 ${r.status}），请查看服务端日志`)}if(!r.ok)throw new Error(errorMessage(body.detail,r.status));historyBody=body;planData=body;animation=null;input('summary').innerHTML=`<h2>规划结果</h2><p><strong>双机规划耗时：${body.planning_time_s.toFixed(3)} 秒</strong></p>`+body.drones.map((d,i)=>{const s=d.summary,status=s.coverage_requirement_met?'可执行':'覆盖不足，不可执行',method=s.coverage_generation_method??s.scan_pattern,cellNote=method==='bcd'?`<br>BCD cells：${(s.coverage_cells??[]).length} 个`:'',completionNote=`<br>飞行前补全点：${(s.completion_points??[]).length} 个`,pointNote=s.unreachable_candidate_point_count?`<br>初始候选点不可达：${s.unreachable_candidate_point_count} 个（${s.uncovered_patch_count?'仍有地面未覆盖':'已由飞行前覆盖补全'}）`:'',worstNote=s.worst_patch_id?`<br>最差 patch：${s.worst_patch_id}，${(100*s.worst_patch_coverage_ratio).toFixed(6)}%`:'';return`<p><strong style="color:${colors[i]}">无人机 ${i+1}</strong><br>任务状态：${status}<br>覆盖生成：${strategyNames[method]??method}${cellNote}${completionNote}<br>补全策略：${s.completion_strategy}<br>路径优化：${s.route_optimization_method}<br>全局覆盖率：${(100*s.coverage_ratio).toFixed(6)}%（单 patch 要求 ${(100*s.minimum_required_coverage_ratio).toFixed(4)}%）${worstNote}<br>未覆盖面积：${s.uncovered_area_m2.toFixed(6)} 平方米<br>最终未覆盖网格：${s.uncovered_patch_count} 个${pointNote}<br>总航程：${s.path_length_m.toFixed(0)} 米<br>Coverage lanes：${s.lane_count} 条<br>飞控途径点：${s.flight_waypoint_count} 个<br>视野计算样本：${s.visibility_sample_count} 个</p>`}).join('');input('exports').innerHTML='<a href="/api/export/mission_manifest.json">双机任务清单（JSON）</a>'+body.drones.map((d,i)=>`<p><strong>无人机 ${i+1}</strong><br><a href="/api/export/${d.drone_id}/flight_plan.json">飞控计划（JSON）</a><br><a href="/api/export/${d.drone_id}/coverage_report.json">覆盖报告（JSON）</a><br><a href="/api/export/${d.drone_id}/visualization.png">规划结果图（PNG）</a></p>`).join('');draw();input('replay').disabled=false}catch(e){historyError=e.message;input('error').textContent=e.message;input('error').style.display='block'}finally{const elapsed=stopPlanningTimer(startedAt);addPlanningHistory(historyBody,elapsed,historyError);button.disabled=false;button.textContent='生成并优化两架无人机航线'}};
async function load(){try{const r=await fetch('/api/map');mapData=await r.json();configureViewport();defaultRegions();draw()}catch(e){input('error').textContent='地图加载失败，请确认规划服务正在运行。';input('error').style.display='block'}}load();
